routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/login', function () {
    return view('auth/login');
})->name('login');

Route::resource('article', 'App\Http\Controllers\User\ArticleController');
Route::get('/', function () {
    return redirect('/article');
});

// Admin Auth  
Route::group(['middleware'=>'auth'],function () {
    Route::resource('admin_article', 'App\Http\Controllers\Admin\ArticleController');
    Route::get('/admin', function () {
        return redirect('/admin_article');
    });

});  




Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::post('/loginController', [App\Http\Controllers\AuthController::class, 'login'])->name('loginController');
Route::get('/logout', [App\Http\Controllers\AuthController::class, 'logout'])->name('logout');

app/Models/article.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class article extends Model
{
    use HasFactory;

    protected $fillable = [
        'title',
        'bio',
        'text',
        'user_id',
        'created_at',
        'updated_at',
    ];

    public function User()
    {
        return $this->belongsTo('App\Models\User', 'user_id');
    }
    public function images()
    {
        return $this->hasMany('App\Models\image');
    }
}

app/Http/Controllers/Admin/ArticleController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\Auth;
use App\Http\Services\ArticleService;

use App\Http\Controllers\Controller;

class ArticleController extends Controller
{

    protected $articleService;
    public function __construct(ArticleService $articleService)
    {
        $this->articleService = $articleService;
        //$this->middleware('ApiAuth:api');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        try{
            $articles = $this->articleService->getAll();
            $result = [
                'code' => 200,
                'data' => $articles,
                'error' => null
            ];
            return view('admin/articleList', compact('result'));
        } catch(Exception $e){
            $result = [
                'code' => 401,
                'data' => null,
                'error' => $e->getMessage()
            ];
            return view('admin/articleList', compact('result'));
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin/addArticle');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = $request->only([
            'title',
            'bio',
            'text',
            'my_file'
        ]);

        $error = null;
        try{
            $article = $this->articleService->add($data);
            if(!$article) {
                $error = 'something went wrong';
            }
        } catch(Exception $e){
            $error = $e->getMessage();
        }

        // return to article List
        try{
            $articles = $this->articleService->getAll();
            $result = [
                'code' => 401,
                'data' => $articles,
                'error' => $error
            ];
            return view('admin/articleList', compact('result'));
        } catch(Exception $e){
            $result = [
                'code' => 402,
                'data' => null,
                'error' => $e->getMessage()
            ];
            return view('admin/articleList', compact('result'));
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        try{
            $article = $this->articleService->getById($id);
            if($article->user_id == Auth::user()->id) {
                $result = [
                    'code' => 200,
                    'data' => $article,
                    'error' => null
                ];
                return view('admin/editArticle', compact('result'));
            }else{
                $error = 'you are not the owner!';
            }
        } catch(Exception $e){
            $error = $e->getMessage();
        }

        $articles = $this->articleService->getAll();

        $result = [
            'code' => 401,
            'data' => $articles,
            'error' => $error
        ];

        return view('admin/articleList', compact('result'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $data = $request->only([
            'title',
            'bio',
            'text',
//            'my_file'
        ]);

        $error = null;
        try{
            $article = $this->articleService->getById($id);
            if($article->user_id == Auth::user()->id) {
                $article = $this->articleService->update($data, $id);
                if (!$article) {
                    $error = 'something went wrong';
                }
            }else{
                $error = 'you are not the owner!';
            }
        } catch(Exception $e){
            $error = $e->getMessage();
        }

        // return to article List
        try{
            $articles = $this->articleService->getAll();
            $result = [
                'code' => 401,
                'data' => $articles,
                'error' => $error
            ];
            return view('admin/articleList', compact('result'));
        } catch(Exception $e){
            $result = [
                'code' => 402,
                'data' => null,
                'error' => $e->getMessage()
            ];
            return view('admin/articleList', compact('result'));
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        try{
            $article = $this->articleService->getById($id);
            if($article->user_id == Auth::user()->id) {
                $articles = $this->articleService->deleteArticle($id);
                $result = [
                    'code' => 200,
                    'data' => null,
                    'error' => null
                ];
                return view('admin/articleList', compact('result'));
            }else{
                $result = [
                    'code' => 200,
                    'data' => null,
                    'error' => 'you are not the owner!'
                ];
                return view('admin/articleList', compact('result'));
            }
        } catch(Exception $e){
            $result = [
                'code' => 401,
                'data' => null,
                'error' => $e->getMessage()
            ];
            return view('admin/articleList', compact('result'));
        }
    }
}

app/Http/Controllers/User/ArticleController.php
<?php

namespace App\Http\Controllers\User;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;

use App\Http\Services\ArticleService;
use App\Http\Controllers\Controller;

class ArticleController extends Controller
{

    protected $articleService;
    public function __construct(ArticleService $articleService)
    {
        $this->articleService = $articleService;
        //$this->middleware('ApiAuth:api');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        try{
            $articles = $this->articleService->getAll();
            $result = [
                'code' => 200,
                'data' => $articles,
                'error' => null
            ];
            return view('article/articlesList', compact('result'));
        } catch(Exception $e){
            $result = [
                'code' => 401,
                'data' => null,
                'error' => $e->getMessage()
            ];
            return view('article/articlesList', compact('result'));
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        try{
            $article = $this->articleService->getById($id);
            if($article) {
                $result = [
                    'code' => 200,
                    'data' => $article,
                    'error' => null
                ];
                return view('article/article', compact('result'));
            }else{
                $articles = $this->articleService->getAll();
                $result = [
                    'code' => 200,
                    'data' => $articles,
                    'error' => null
                ];
                return view('article/articlesList', compact('result'));
            }
        } catch(Exception $e){
            $result = [
                'code' => 401,
                'data' => null,
                'error' => $e->getMessage()
            ];
            return view('article/article', compact('result'));
        }
        return view('article/article');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/article/article.blade.php
@include('article.header')
<body>

@include('article.navbar')

<div class="container">
    <section>
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                    <ul class="bxslider">
                        @foreach($result['data']->images as $image)
                            <?php $path = 'images/medium_size/' . $image->name; ?>
                            <li><div class="slider-item"><img class="slider-article-img" src="{{asset($path)}}" title="Funky roots" /></div></li>
                        @endforeach
                    </ul>
                <article class="blog-post">
                    <div class="blog-post-image">
                        <a href="post.html"><img src="{{asset('Articles/images/750x500-5.jpg')}}" alt=""></a>
                    </div>
                    <div class="blog-post-body">
                        <h2><a href="post.html">{{$result['data']->title}}</a></h2>
                        <div class="post-meta"><span>by {{$result['data']->username}}</span>/<span><i class="fa fa-clock-o"></i>posted in {{$result['data']->created_at->format('Y-m-d')}}</span></div>
                        <div class="blog-post-text">
                            <?php echo $result['data']->text; ?>
                        </div>
                    </div>
                </article>
            </div>
        </div>
    </section>
</div><!-- /.container -->

@include('article.footer')

resources/views/article/articlesList.blade.php
@include('article.header')
<body>

@include('article.navbar')

<div class="container">
    <header>
        <a href="{{route('article.index')}}"><h1 class="title">DownTown</h1></a>
    </header>
    <section class="main-slider">
        <ul class="bxslider">
            <li><div class="slider-item"><img class="slider-img" src="{{asset('Articles/images/slider1.jpeg')}}" title="Funky roots" /><h2><a href="{{route('article.index')}}" title="Vintage-Inspired Finds for Your Home">Today a reader, tomorrow a leader</a></h2></div></li>
            <li><div class="slider-item"><img class="slider-img" src="{{asset('Articles/images/slider2.jpeg')}}" title="Funky roots" /><h2><a href="{{route('article.index')}}" title="Vintage-Inspired Finds for Your Home">Reading one book is like eating one potato chip</a></h2></div></li>
            <li><div class="slider-item"><img class="slider-img" src="{{asset('Articles/images/slider3.jpeg')}}" title="Funky roots" /><h2><a href="{{route('article.index')}}" title="Vintage-Inspired Finds for Your Home">Think before you speak. Read before you think</a></h2></div></li>
        </ul>
    </section>
    <hr class="first-line">
    <section>
        <div class="row">
            <div class="col-md-12">
                @if($result['data'])
                    @foreach($result['data'] as $item)
                        <article class="blog-post">
                            <div class="blog-post-image">
                                @if($item->images)
                                    @if(sizeof($item->images))
                                        <a href="{{route('article.show', $item->id)}}">
                                            <?php $path = 'images/medium_size/' . $item->images[0]->name; ?>
                                            <img class="articles-img" src="{{asset($path)}}" alt="">
                                        </a>
                                    @endif
                                @endif
                            </div>
                            <div class="blog-post-body">
                                <h2><a href="{{route('article.show', $item->id)}}">{{$item->title}}</a></h2>
                                <div class="post-meta"><span>by {{$item->username}}</span>/<span><i class="fa fa-clock-o"></i>posted in {{$item->created_at->format('Y-m-d')}}</span></div>
                                <p>{{$item->bio}}</p>
                                <div class="read-more"><a href="{{route('article.show', $item->id)}}">Continue Reading</a></div>
                            </div>
                        </article>
                    @endforeach
                @endif
            </div>
        </div>
    </section>
</div><!-- /.container -->

@include('article.footer')

resources/views/article/footer.blade.php
<footer class="footer">

    <div class="footer-socials">
        <a href="#"><i class="fa fa-facebook"></i></a>
        <a href="#"><i class="fa fa-twitter"></i></a>
        <a href="#"><i class="fa fa-instagram"></i></a>
        <a href="#"><i class="fa fa-google-plus"></i></a>
        <a href="#"><i class="fa fa-dribbble"></i></a>
        <a href="#"><i class="fa fa-reddit"></i></a>
    </div>


</footer>

<!-- Bootstrap core JavaScript
    ================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script src="{{asset('Articles/js/bootstrap.min.js')}}"></script>
<script src="{{asset('Articles/js/jquery.bxslider.js')}}"></script>
<script src="{{asset('Articles/js/mooz.scripts.min.js')}}"></script>
</body>
</html>

resources/views/article/header.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="favicon.ico">
    <title>Renda - clean blog theme based on Bootstrap</title>
    <!-- Bootstrap core CSS -->
    <link href="{{asset('Articles/css/bootstrap.min.css')}}" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <!-- Custom styles for this template -->
    <link href="{{asset('Articles/css/jquery.bxslider.css')}}" rel="stylesheet">
    <link href="{{asset('Articles/css/style.css')}}" rel="stylesheet">

    <style>
        .title{
            font-size: 50px;
        }
        .slider-img{
            max-height: 607px;
            width: 100%;
        }
        .slider-article-img{
            max-height: 400x;
            width: 100%;
        }
        .articles-img{
            max-height: 500px;
            width: 100%;
        }
        .first-line{
            margin-bottom: 100px;
        }
    </style>
</head>

resources/views/article/navbar.blade.php
<!-- Navigation -->
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li class="active"><a href="{{route('article.index')}}">Home</a></li>
                {{--<li><a href="#about">Lifestyle</a></li>--}}
                {{--<li><a href="#contact">Travel</a></li>--}}
                {{--<li><a href="#contact">Fashion</a></li>--}}
                {{--<li><a href="about.html">About Me</a></li>--}}
                {{--<li><a href="about.html">Contact</a></li>--}}
            </ul>

            <ul class="nav navbar-nav navbar-right">
                <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                <li><a href="#"><i class="fa fa-instagram"></i></a></li>
                <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
                <li><a href="#"><i class="fa fa-dribbble"></i></a></li>
                <li><a href="#"><i class="fa fa-reddit"></i></a></li>
            </ul>

        </div>
        <!--/.nav-collapse -->
    </div>
</nav>