routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/login', function () {
    return view('auth/login');
})->name('login');

Route::resource('article', 'App\Http\Controllers\User\ArticleController');
Route::get('/', function () {
    return redirect('/article');
});

// Admin Auth  
Route::group(['middleware'=>'auth'],function () {
    Route::resource('admin_article', 'App\Http\Controllers\Admin\ArticleController');
    Route::get('/admin', function () {
        return redirect('/admin_article');
    });

});  




Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::post('/loginController', [App\Http\Controllers\AuthController::class, 'login'])->name('loginController');
Route::get('/logout', [App\Http\Controllers\AuthController::class, 'logout'])->name('logout');

resources/views/admin/addArticle.blade.php
@extends('admin.app')

@section('title', 'Add Article')

@section('content')

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">@lang('admin.add_article')</h1>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <section class="content">

        <!-- Main content -->
        <section class="content">
            <div class="row">
                <div class="col-md-12">
                    <div class="card card-outline card-info">
                        <div class="card-header">
                            <h3 class="card-title">
                                @lang('admin.add_article')
                            </h3>
                        </div>
                        <!-- /.card-header -->
                        <div class="card-body">
                            <form id="addArticleForm" method="post" action="{{ route('admin_article.store') }}" enctype="multipart/form-data">
                                @csrf
                                <div class="form-group">
                                    <label>@lang('admin.title')</label>
                                    <input type="text" name="title" class="form-control" placeholder="@lang('admin.enter')">
                                </div>
                                <div class="form-group">
                                    <label>@lang('admin.images')</label>
                                    <input type="file" name="my_file[]" required multiple>
                                </div>
                                <div class="form-group">
                                    <label>Bio</label>
                                    <textarea class="form-control" name="bio" rows="3" placeholder="@lang('admin.enter')"></textarea>
                                </div>
                                <div class="form-group">
                                    <label>@lang('admin.text')</label>
                                      <textarea id="summernote" >
                                            
                                      </textarea>
                                    <input type="text" name="text" id="text" class="form-control" placeholder="@lang('admin.enter')" hidden>
                                </div>
                                <button type="submit" id="addArticleBtn" class="btn btn-block btn-primary" style="width: 10%; float: right">@lang('admin.submit')</button>
                            </form>
                        </div>
                        <div class="card-footer">
                        </div>
                    </div>
                </div>
                <!-- /.col-->
            </div>
            <!-- ./row -->
            <div class="row">
                <div class="col-md-12">
                    <div class="card card-outline card-info">
                        <div class="card-header">
                            <h3 class="card-title">
                                CodeMirror
                            </h3>
                        </div>
                        <!-- /.card-header -->
                        <div class="card-body p-0">
              <textarea id="codeMirrorDemo" class="p-3">
              </textarea>
                            <button type="button" id="convertBtn" class="btn btn-block btn-primary" style="width: 10%; float: right">Convert</button>
                        </div>
                        <div class="card-footer">
                        </div>
                    </div>
                </div>
                <!-- /.col-->
            </div>
            <!-- ./row -->
        </section>
        <!-- /.content -->
    </section>
</div>
@endsection
@section('js')
    <script>
        $( document ).ready(function() {
            $('#sidebar *').removeClass('active');
            $('#add a').addClass('active');
            $('#summernote').summernote('code', '<p></p>');

            document.querySelector('.CodeMirror').CodeMirror.setValue($('#summernote').summernote('code'));

            $('#addArticleBtn').click(function (e) {
                e.preventDefault();
                console.log('sss', $('#summernote').summernote('code'));
                if($('#summernote').summernote('code') === ''){
                    $('#summernote').summernote('code', '<p></p>');
                }
                $('#text').val($('#summernote').summernote('code'));
                $('#addArticleForm').submit();
                //document.querySelector('.CodeMirror').CodeMirror.setValue($('#summernote').summernote('code'));
            });
            $('#convertBtn').click(function () {
                document.querySelector('.CodeMirror').CodeMirror.setValue($('#summernote').summernote('code'));
            });
            //validation
            $('#addArticleForm').validate({
                rules: {
                title: {
                    required: true
                },
                my_file: {
                    required: true
                },
                bio: {
                    required: true
                },
                },
                messages: {
                    title: {
                    required: "Title is required"
                },
                my_file: {
                    required: "Images are required"
                },
                bio: {
                    required: "Bio is required"
                },
                },
                errorElement: 'span',
                errorPlacement: function (error, element) {
                error.addClass('invalid-feedback');
                element.closest('.form-group').append(error);
                },
                highlight: function (element, errorClass, validClass) {
                $(element).addClass('is-invalid');
                },
                unhighlight: function (element, errorClass, validClass) {
                $(element).removeClass('is-invalid');
                }
            });
            $('input[name^="file[]"]').each(function () {
                $(this).rules('add', {
                    required: true,
                    accept: "image/jpeg, image/pjpeg"
                })
            })
        });
    </script>
@endsection

resources/views/admin/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}" />
    <title>@yield('title')</title>

    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="{{asset('AdminLTE/plugins/fontawesome-free/css/all.min.css')}}">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Tempusdominus Bootstrap 4 -->
    <link rel="stylesheet" href="{{asset('AdminLTE/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css')}}">
    <!-- iCheck -->
    <link rel="stylesheet" href="{{asset('AdminLTE/plugins/icheck-bootstrap/icheck-bootstrap.min.css')}}">
    <!-- JQVMap -->
    <link rel="stylesheet" href="{{asset('AdminLTE/plugins/jqvmap/jqvmap.min.css')}}">
    <!-- Theme style -->
    <link rel="stylesheet" href="{{asset('AdminLTE/dist/css/adminlte.min.css')}}">
    <!-- overlayScrollbars -->
    <link rel="stylesheet" href="{{asset('AdminLTE/plugins/overlayScrollbars/css/OverlayScrollbars.min.css')}}">
    <!-- Daterange picker -->
    <link rel="stylesheet" href="{{asset('AdminLTE/plugins/daterangepicker/daterangepicker.css')}}">
    <!-- summernote -->
    <link rel="stylesheet" href="{{asset('AdminLTE/plugins/summernote/summernote-bs4.min.css')}}">

    <!-- CodeMirror -->
    <link rel="stylesheet" href="{{asset('AdminLTE/plugins/codemirror/codemirror.css')}}">
    <link rel="stylesheet" href="{{asset('AdminLTE/plugins/codemirror/theme/monokai.css')}}">
    <!-- SimpleMDE -->
    <link rel="stylesheet" href="{{asset('AdminLTE/plugins/simplemde/simplemde.min.css')}}">
</head>
<body>

    <!-- Navbar -->
    <nav class="main-header navbar navbar-expand navbar-white navbar-light">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
            </li>
        </ul>
        <ul class="navbar-nav ml-auto">
            <li class="nav-item d-none d-sm-inline-block">
                <a href="{{ route('logout') }}" class="nav-link">Logout</a>
            </li>
        </ul>
    </nav>
    <!-- /.navbar -->
    @include('admin.sidebar')

    @yield('content')
    
    @include('admin.footer')
    @yield('js')
    </body>
</html>

resources/views/admin/articleList.blade.php
@extends('admin.app')

@section('title', 'Article List')

@section('content')
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <div class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-12">
                        @if($result['error'] && $result['code'] == 401)
                            <div class="alert alert-danger alert-dismissible">
                                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                                <h5><i class="icon fas fa-ban"></i> Alert!</h5>
                                <span>{{$result['error']}}</span>
                            </div>
                        @endif
                        @if(!$result['error'] && $result['code'] == 401)
                            <div class="alert alert-success alert-dismissible">
                                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                                <h5><i class="icon fas fa-check"></i> Alert!</h5>
                                your request has been done successfuly!
                            </div>
                        @endif
                    </div>
                    <div class="col-sm-6">
                        <h1 class="m-0">Articles</h1>
                    </div><!-- /.col -->
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="#">Home</a></li>
                            <li class="breadcrumb-item active">Dashboard v1</li>
                        </ol>
                    </div><!-- /.col -->
                </div><!-- /.row -->
            </div><!-- /.container-fluid -->
        </div>
        <!-- /.content-header -->

        <!-- Main content -->
        <section class="content">
            <!-- Main content -->
            <section class="content">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-12">


                            <div class="card">
                                <div class="card-header">
                                    <h3 class="card-title">@lang('admin.articles_table')</h3>
                                </div>
                                <!-- /.card-header -->
                                <div class="card-body">
                                    <table id="example1" class="table table-bordered table-striped">
                                        <thead>
                                        <tr>
                                            <th>@lang('admin.title')</th>
                                            <th>@lang('admin.bio')</th>
                                            <th>@lang('admin.text')</th>
                                            <th>@lang('admin.user')</th>
                                            <th>@lang('admin.created_at')</th>
                                            <th>@lang('admin.edit')</th>
                                            <th>@lang('admin.delete')</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        @if($result['data'])
                                            @foreach($result['data'] as $item)
                                            <tr>
                                                <td>{{$item->title}}</td>
                                                <td>{{Str::limit($item->bio, 20)}}</td>
                                                <td>{{Str::limit($item->text, 20)}}</td>
                                                <td>{{$item->username}}</td>
                                                <td>{{$item->created_at->format('Y-m-d')}}</td>
                                                <td>
                                                    @if(Auth::user()->id == $item->user_id)
                                                        <a href="{{route('admin_article.edit', $item->id)}}"><button type="button" id="editArticleBtn" class="btn btn-block btn-success" >@lang('admin.edit')</button></a>
                                                    @else
                                                        <p style="color: red">you are not the owner</p>
                                                    @endif
                                                </td>
                                                <td>
                                                    @if(Auth::user()->id == $item->user_id)
                                                        <a onclick="DeleteItem('{{ url('admin_article/'. $item->id ) }}')" title="delete" href="javascript:;" class="btn btn-danger"><i class="fas fa-trash"></i></a>
                                                    @else
                                                        <p style="color: red">you are not the owner</p>
                                                    @endif
                                                </td>
                                            </tr>
                                            @endforeach
                                        @endif

                                        </tbody>
                                        <tfoot>
                                        <tr>
                                            <th>@lang('admin.title')</th>
                                            <th>@lang('admin.bio')</th>
                                            <th>@lang('admin.text')</th>
                                            <th>@lang('admin.user')</th>
                                            <th>@lang('admin.created_at')</th>
                                            <th>@lang('admin.edit')</th>
                                            <th>@lang('admin.delete')</th>
                                        </tr>
                                        </tfoot>
                                    </table>
                                </div>
                                <!-- /.card-body -->
                            </div>
                            <!-- /.card -->
                        </div>
                        <!-- /.col -->
                    </div>
                    <!-- /.row -->
                </div>
                <!-- /.container-fluid -->
            </section>
            <!-- /.content -->
        </section>
        <!-- /.content -->
    </div>
@endsection
@section('js')
    <script>
            $( document ).ready(function() {
                $('#sidebar *').removeClass('active');
                $('#list a').addClass('active');
                });

                function DeleteItem(url) {
                    Swal.fire({
                        title:"Are you sure?",
                        icon: "warning",
                        showCancelButton: true,
                        confirmButtonColor: '#3085d6',
                        cancelButtonColor: '#d33',
                        confirmButtonText: 'Delete',
                        cancelButtonText: 'Cancel',
                        }).then((willDelete) => {
                        if (willDelete.value) {
                            console.log(url);
                            $.ajax({
                                type: "DELETE",
                                url: url,
                                headers: {
                                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                                },
                                dataType: 'json',
                                contentType: "application/json; charset=utf-8",
                                success: function (res) {
                                    location.reload();
                                },
                                error: function (data, response) {
                                    location.reload();

                                },
                            });
                        }
                        });
                    }
            
    </script>
@endsection

resources/views/admin/editArticle.blade.php
@extends('admin.app')

@section('title', 'Edit Article')

@section('content')

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">@lang('admin.edit_article')</h1>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->
<?php //dd($result); ?>
    <!-- Main content -->
    <section class="content">

        <!-- Main content -->
        <section class="content">
            <div class="row">
                <div class="col-md-12">
                    <div class="card card-outline card-info">
                        <div class="card-header">
                            <h3 class="card-title">
                                @lang('admin.edit_article')
                            </h3>
                        </div>
                        <!-- /.card-header -->
                        <div class="card-body">
                            <form id="editArticleForm" method="post" action="{{ url('/admin_article/' . $result['data']['id']) }}" enctype="multipart/form-data">
                                @csrf
                                @method('PUT')
                                <div class="form-group">
                                    <label>@lang('admin.title')</label>
                                    <input type="text" name="title" class="form-control" placeholder="@lang('admin.enter')" value="{{$result['data']['title']}}">
                                </div>
                                <div class="form-group">
                                    <label>@lang('admin.images')</label>
                                    <input type="file" name="my_file[]" required multiple>
                                </div>
                                <div class="form-group">
                                    <label>Bio</label>
                                    <textarea class="form-control" name="bio" rows="3" placeholder="@lang('admin.enter')">
                                        <?php echo $result['data']['bio']; ?>
                                    </textarea>
                                </div>
                                <div class="form-group">
                                    <label>@lang('admin.text')</label>
                                      <textarea id="summernote" >
                                            <?php echo $result['data']['text']; ?>
                                      </textarea>
                                    <input type="text" name="text" id="text" class="form-control" placeholder="@lang('admin.enter')" hidden>
                                </div>
                                <button type="submit" id="editArticleBtn" class="btn btn-block btn-primary" style="width: 10%; float: right">@lang('admin.submit')</button>
                            </form>
                        </div>
                        <div class="card-footer">
                        </div>
                    </div>
                </div>
                <!-- /.col-->
            </div>
            <!-- ./row -->
            <div class="row">
                <div class="col-md-12">
                    <div class="card card-outline card-info">
                        <div class="card-header">
                            <h3 class="card-title">
                                CodeMirror
                            </h3>
                        </div>
                        <!-- /.card-header -->
                        <div class="card-body p-0">
              <textarea id="codeMirrorDemo" class="p-3">
              </textarea>
                            <button type="button" id="convertBtn" class="btn btn-block btn-primary" style="width: 10%; float: right">Convert</button>
                        </div>
                        <div class="card-footer">
                        </div>
                    </div>
                </div>
                <!-- /.col-->
            </div>
            <!-- ./row -->
        </section>
        <!-- /.content -->
    </section>
</div>
@endsection
@section('js')
    <script>
        $( document ).ready(function() {
            $('#sidebar *').removeClass('active');
            $('#add a').addClass('active');

            document.querySelector('.CodeMirror').CodeMirror.setValue($('#summernote').summernote('code'));

            $('#editArticleBtn').click(function (e) {
                e.preventDefault();
                console.log($('#summernote').summernote('code'));
                $('#text').val($('#summernote').summernote('code'));
                if($('#summernote').summernote('code') === ''){
                    $('#summernote').summernote('code', '<p></p>');
                }
                $('#editArticleForm').submit();
                //document.querySelector('.CodeMirror').CodeMirror.setValue($('#summernote').summernote('code'));
            });
            $('#convertBtn').click(function () {
                document.querySelector('.CodeMirror').CodeMirror.setValue($('#summernote').summernote('code'));
            });
            //validation
            $('#editArticleForm').validate({
                rules: {
                    title: {
                        required: true
                    },
                    my_file: {
                        required: true
                    },
                    bio: {
                        required: true
                    },
                },
                messages: {
                    title: {
                        required: "Title is required"
                    },
                    my_file: {
                        required: "Images are required"
                    },
                    bio: {
                        required: "Bio is required"
                    },
                },
                errorElement: 'span',
                errorPlacement: function (error, element) {
                    error.addClass('invalid-feedback');
                    element.closest('.form-group').append(error);
                },
                highlight: function (element, errorClass, validClass) {
                    $(element).addClass('is-invalid');
                },
                unhighlight: function (element, errorClass, validClass) {
                    $(element).removeClass('is-invalid');
                }
            });
        });
    </script>
@endsection

resources/views/admin/header.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>AdminLTE 3 | Dashboard</title>

    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="{{asset('AdminLTE/plugins/fontawesome-free/css/all.min.css')}}">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Tempusdominus Bootstrap 4 -->
    <link rel="stylesheet" href="{{asset('AdminLTE/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css')}}">
    <!-- iCheck -->
    <link rel="stylesheet" href="{{asset('AdminLTE/plugins/icheck-bootstrap/icheck-bootstrap.min.css')}}">
    <!-- JQVMap -->
    <link rel="stylesheet" href="{{asset('AdminLTE/plugins/jqvmap/jqvmap.min.css')}}">
    <!-- Theme style -->
    <link rel="stylesheet" href="{{asset('AdminLTE/dist/css/adminlte.min.css')}}">
    <!-- overlayScrollbars -->
    <link rel="stylesheet" href="{{asset('AdminLTE/plugins/overlayScrollbars/css/OverlayScrollbars.min.css')}}">
    <!-- Daterange picker -->
    <link rel="stylesheet" href="{{asset('AdminLTE/plugins/daterangepicker/daterangepicker.css')}}">
    <!-- summernote -->
    <link rel="stylesheet" href="{{asset('AdminLTE/plugins/summernote/summernote-bs4.min.css')}}">

    <!-- CodeMirror -->
    <link rel="stylesheet" href="{{asset('AdminLTE/plugins/codemirror/codemirror.css')}}">
    <link rel="stylesheet" href="{{asset('AdminLTE/plugins/codemirror/theme/monokai.css')}}">
    <!-- SimpleMDE -->
    <link rel="stylesheet" href="{{asset('AdminLTE/plugins/simplemde/simplemde.min.css')}}">
</head>

resources/views/admin/sidebar.blade.php
<!-- Main Sidebar Container -->
<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <!-- <a href="index3.html" class="brand-link">
        <span class="brand-text font-weight-light">Articles</span>
    </a> -->

    <!-- Sidebar -->
    <div class="sidebar">

        <!-- Sidebar Menu -->
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                <!-- Add icons to the links using the .nav-icon class
                     with font-awesome or any other icon font library -->
                <li class="nav-item menu-open">
                    <ul class="nav nav-treeview" id="sidebar">
                        <li class="nav-item" id="list">
                            <a href="{{route('admin_article.index')}}" class="nav-link">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Articles List</p>
                            </a>
                        </li>
                        <li class="nav-item" id="add">
                            <a href="{{route('admin_article.create')}}" class="nav-link">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Add Articles</p>
                            </a>
                        </li>
                    </ul>
                </li>

            </ul>
        </nav>
        <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
</aside>